# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.22.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jakemartin/documents/monte-carlo-ray-tracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jakemartin/documents/monte-carlo-ray-tracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jakemartin/documents/monte-carlo-ray-tracer/CMakeFiles /Users/jakemartin/documents/monte-carlo-ray-tracer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jakemartin/documents/monte-carlo-ray-tracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named monte-carlo-ray-tracer

# Build rule for target.
monte-carlo-ray-tracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 monte-carlo-ray-tracer
.PHONY : monte-carlo-ray-tracer

# fast build rule for target.
monte-carlo-ray-tracer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/build
.PHONY : monte-carlo-ray-tracer/fast

source/bvh/bvh.o: source/bvh/bvh.cpp.o
.PHONY : source/bvh/bvh.o

# target to build an object file
source/bvh/bvh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/bvh/bvh.cpp.o
.PHONY : source/bvh/bvh.cpp.o

source/bvh/bvh.i: source/bvh/bvh.cpp.i
.PHONY : source/bvh/bvh.i

# target to preprocess a source file
source/bvh/bvh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/bvh/bvh.cpp.i
.PHONY : source/bvh/bvh.cpp.i

source/bvh/bvh.s: source/bvh/bvh.cpp.s
.PHONY : source/bvh/bvh.s

# target to generate assembly for a file
source/bvh/bvh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/bvh/bvh.cpp.s
.PHONY : source/bvh/bvh.cpp.s

source/camera/camera.o: source/camera/camera.cpp.o
.PHONY : source/camera/camera.o

# target to build an object file
source/camera/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/camera/camera.cpp.o
.PHONY : source/camera/camera.cpp.o

source/camera/camera.i: source/camera/camera.cpp.i
.PHONY : source/camera/camera.i

# target to preprocess a source file
source/camera/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/camera/camera.cpp.i
.PHONY : source/camera/camera.cpp.i

source/camera/camera.s: source/camera/camera.cpp.s
.PHONY : source/camera/camera.s

# target to generate assembly for a file
source/camera/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/camera/camera.cpp.s
.PHONY : source/camera/camera.cpp.s

source/camera/image.o: source/camera/image.cpp.o
.PHONY : source/camera/image.o

# target to build an object file
source/camera/image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/camera/image.cpp.o
.PHONY : source/camera/image.cpp.o

source/camera/image.i: source/camera/image.cpp.i
.PHONY : source/camera/image.i

# target to preprocess a source file
source/camera/image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/camera/image.cpp.i
.PHONY : source/camera/image.cpp.i

source/camera/image.s: source/camera/image.cpp.s
.PHONY : source/camera/image.s

# target to generate assembly for a file
source/camera/image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/camera/image.cpp.s
.PHONY : source/camera/image.cpp.s

source/camera/pixel-operators.o: source/camera/pixel-operators.cpp.o
.PHONY : source/camera/pixel-operators.o

# target to build an object file
source/camera/pixel-operators.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/camera/pixel-operators.cpp.o
.PHONY : source/camera/pixel-operators.cpp.o

source/camera/pixel-operators.i: source/camera/pixel-operators.cpp.i
.PHONY : source/camera/pixel-operators.i

# target to preprocess a source file
source/camera/pixel-operators.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/camera/pixel-operators.cpp.i
.PHONY : source/camera/pixel-operators.cpp.i

source/camera/pixel-operators.s: source/camera/pixel-operators.cpp.s
.PHONY : source/camera/pixel-operators.s

# target to generate assembly for a file
source/camera/pixel-operators.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/camera/pixel-operators.cpp.s
.PHONY : source/camera/pixel-operators.cpp.s

source/common/bounding-box.o: source/common/bounding-box.cpp.o
.PHONY : source/common/bounding-box.o

# target to build an object file
source/common/bounding-box.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/bounding-box.cpp.o
.PHONY : source/common/bounding-box.cpp.o

source/common/bounding-box.i: source/common/bounding-box.cpp.i
.PHONY : source/common/bounding-box.i

# target to preprocess a source file
source/common/bounding-box.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/bounding-box.cpp.i
.PHONY : source/common/bounding-box.cpp.i

source/common/bounding-box.s: source/common/bounding-box.cpp.s
.PHONY : source/common/bounding-box.s

# target to generate assembly for a file
source/common/bounding-box.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/bounding-box.cpp.s
.PHONY : source/common/bounding-box.cpp.s

source/common/coordinate-system.o: source/common/coordinate-system.cpp.o
.PHONY : source/common/coordinate-system.o

# target to build an object file
source/common/coordinate-system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/coordinate-system.cpp.o
.PHONY : source/common/coordinate-system.cpp.o

source/common/coordinate-system.i: source/common/coordinate-system.cpp.i
.PHONY : source/common/coordinate-system.i

# target to preprocess a source file
source/common/coordinate-system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/coordinate-system.cpp.i
.PHONY : source/common/coordinate-system.cpp.i

source/common/coordinate-system.s: source/common/coordinate-system.cpp.s
.PHONY : source/common/coordinate-system.s

# target to generate assembly for a file
source/common/coordinate-system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/coordinate-system.cpp.s
.PHONY : source/common/coordinate-system.cpp.s

source/common/format.o: source/common/format.cpp.o
.PHONY : source/common/format.o

# target to build an object file
source/common/format.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/format.cpp.o
.PHONY : source/common/format.cpp.o

source/common/format.i: source/common/format.cpp.i
.PHONY : source/common/format.i

# target to preprocess a source file
source/common/format.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/format.cpp.i
.PHONY : source/common/format.cpp.i

source/common/format.s: source/common/format.cpp.s
.PHONY : source/common/format.s

# target to generate assembly for a file
source/common/format.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/format.cpp.s
.PHONY : source/common/format.cpp.s

source/common/histogram.o: source/common/histogram.cpp.o
.PHONY : source/common/histogram.o

# target to build an object file
source/common/histogram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/histogram.cpp.o
.PHONY : source/common/histogram.cpp.o

source/common/histogram.i: source/common/histogram.cpp.i
.PHONY : source/common/histogram.i

# target to preprocess a source file
source/common/histogram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/histogram.cpp.i
.PHONY : source/common/histogram.cpp.i

source/common/histogram.s: source/common/histogram.cpp.s
.PHONY : source/common/histogram.s

# target to generate assembly for a file
source/common/histogram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/histogram.cpp.s
.PHONY : source/common/histogram.cpp.s

source/common/option.o: source/common/option.cpp.o
.PHONY : source/common/option.o

# target to build an object file
source/common/option.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/option.cpp.o
.PHONY : source/common/option.cpp.o

source/common/option.i: source/common/option.cpp.i
.PHONY : source/common/option.i

# target to preprocess a source file
source/common/option.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/option.cpp.i
.PHONY : source/common/option.cpp.i

source/common/option.s: source/common/option.cpp.s
.PHONY : source/common/option.s

# target to generate assembly for a file
source/common/option.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/option.cpp.s
.PHONY : source/common/option.cpp.s

source/common/util.o: source/common/util.cpp.o
.PHONY : source/common/util.o

# target to build an object file
source/common/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/util.cpp.o
.PHONY : source/common/util.cpp.o

source/common/util.i: source/common/util.cpp.i
.PHONY : source/common/util.i

# target to preprocess a source file
source/common/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/util.cpp.i
.PHONY : source/common/util.cpp.i

source/common/util.s: source/common/util.cpp.s
.PHONY : source/common/util.s

# target to generate assembly for a file
source/common/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/common/util.cpp.s
.PHONY : source/common/util.cpp.s

source/integrator/integrator.o: source/integrator/integrator.cpp.o
.PHONY : source/integrator/integrator.o

# target to build an object file
source/integrator/integrator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/integrator/integrator.cpp.o
.PHONY : source/integrator/integrator.cpp.o

source/integrator/integrator.i: source/integrator/integrator.cpp.i
.PHONY : source/integrator/integrator.i

# target to preprocess a source file
source/integrator/integrator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/integrator/integrator.cpp.i
.PHONY : source/integrator/integrator.cpp.i

source/integrator/integrator.s: source/integrator/integrator.cpp.s
.PHONY : source/integrator/integrator.s

# target to generate assembly for a file
source/integrator/integrator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/integrator/integrator.cpp.s
.PHONY : source/integrator/integrator.cpp.s

source/integrator/path-tracer/path-tracer.o: source/integrator/path-tracer/path-tracer.cpp.o
.PHONY : source/integrator/path-tracer/path-tracer.o

# target to build an object file
source/integrator/path-tracer/path-tracer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/integrator/path-tracer/path-tracer.cpp.o
.PHONY : source/integrator/path-tracer/path-tracer.cpp.o

source/integrator/path-tracer/path-tracer.i: source/integrator/path-tracer/path-tracer.cpp.i
.PHONY : source/integrator/path-tracer/path-tracer.i

# target to preprocess a source file
source/integrator/path-tracer/path-tracer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/integrator/path-tracer/path-tracer.cpp.i
.PHONY : source/integrator/path-tracer/path-tracer.cpp.i

source/integrator/path-tracer/path-tracer.s: source/integrator/path-tracer/path-tracer.cpp.s
.PHONY : source/integrator/path-tracer/path-tracer.s

# target to generate assembly for a file
source/integrator/path-tracer/path-tracer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/integrator/path-tracer/path-tracer.cpp.s
.PHONY : source/integrator/path-tracer/path-tracer.cpp.s

source/integrator/photon-mapper/photon-mapper.o: source/integrator/photon-mapper/photon-mapper.cpp.o
.PHONY : source/integrator/photon-mapper/photon-mapper.o

# target to build an object file
source/integrator/photon-mapper/photon-mapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/integrator/photon-mapper/photon-mapper.cpp.o
.PHONY : source/integrator/photon-mapper/photon-mapper.cpp.o

source/integrator/photon-mapper/photon-mapper.i: source/integrator/photon-mapper/photon-mapper.cpp.i
.PHONY : source/integrator/photon-mapper/photon-mapper.i

# target to preprocess a source file
source/integrator/photon-mapper/photon-mapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/integrator/photon-mapper/photon-mapper.cpp.i
.PHONY : source/integrator/photon-mapper/photon-mapper.cpp.i

source/integrator/photon-mapper/photon-mapper.s: source/integrator/photon-mapper/photon-mapper.cpp.s
.PHONY : source/integrator/photon-mapper/photon-mapper.s

# target to generate assembly for a file
source/integrator/photon-mapper/photon-mapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/integrator/photon-mapper/photon-mapper.cpp.s
.PHONY : source/integrator/photon-mapper/photon-mapper.cpp.s

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/material/fresnel.o: source/material/fresnel.cpp.o
.PHONY : source/material/fresnel.o

# target to build an object file
source/material/fresnel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/material/fresnel.cpp.o
.PHONY : source/material/fresnel.cpp.o

source/material/fresnel.i: source/material/fresnel.cpp.i
.PHONY : source/material/fresnel.i

# target to preprocess a source file
source/material/fresnel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/material/fresnel.cpp.i
.PHONY : source/material/fresnel.cpp.i

source/material/fresnel.s: source/material/fresnel.cpp.s
.PHONY : source/material/fresnel.s

# target to generate assembly for a file
source/material/fresnel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/material/fresnel.cpp.s
.PHONY : source/material/fresnel.cpp.s

source/material/ggx.o: source/material/ggx.cpp.o
.PHONY : source/material/ggx.o

# target to build an object file
source/material/ggx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/material/ggx.cpp.o
.PHONY : source/material/ggx.cpp.o

source/material/ggx.i: source/material/ggx.cpp.i
.PHONY : source/material/ggx.i

# target to preprocess a source file
source/material/ggx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/material/ggx.cpp.i
.PHONY : source/material/ggx.cpp.i

source/material/ggx.s: source/material/ggx.cpp.s
.PHONY : source/material/ggx.s

# target to generate assembly for a file
source/material/ggx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/material/ggx.cpp.s
.PHONY : source/material/ggx.cpp.s

source/material/material.o: source/material/material.cpp.o
.PHONY : source/material/material.o

# target to build an object file
source/material/material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/material/material.cpp.o
.PHONY : source/material/material.cpp.o

source/material/material.i: source/material/material.cpp.i
.PHONY : source/material/material.i

# target to preprocess a source file
source/material/material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/material/material.cpp.i
.PHONY : source/material/material.cpp.i

source/material/material.s: source/material/material.cpp.s
.PHONY : source/material/material.s

# target to generate assembly for a file
source/material/material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/material/material.cpp.s
.PHONY : source/material/material.cpp.s

source/octree/linear-octree.o: source/octree/linear-octree.cpp.o
.PHONY : source/octree/linear-octree.o

# target to build an object file
source/octree/linear-octree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/octree/linear-octree.cpp.o
.PHONY : source/octree/linear-octree.cpp.o

source/octree/linear-octree.i: source/octree/linear-octree.cpp.i
.PHONY : source/octree/linear-octree.i

# target to preprocess a source file
source/octree/linear-octree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/octree/linear-octree.cpp.i
.PHONY : source/octree/linear-octree.cpp.i

source/octree/linear-octree.s: source/octree/linear-octree.cpp.s
.PHONY : source/octree/linear-octree.s

# target to generate assembly for a file
source/octree/linear-octree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/octree/linear-octree.cpp.s
.PHONY : source/octree/linear-octree.cpp.s

source/octree/octree.o: source/octree/octree.cpp.o
.PHONY : source/octree/octree.o

# target to build an object file
source/octree/octree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/octree/octree.cpp.o
.PHONY : source/octree/octree.cpp.o

source/octree/octree.i: source/octree/octree.cpp.i
.PHONY : source/octree/octree.i

# target to preprocess a source file
source/octree/octree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/octree/octree.cpp.i
.PHONY : source/octree/octree.cpp.i

source/octree/octree.s: source/octree/octree.cpp.s
.PHONY : source/octree/octree.s

# target to generate assembly for a file
source/octree/octree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/octree/octree.cpp.s
.PHONY : source/octree/octree.cpp.s

source/ray/interaction.o: source/ray/interaction.cpp.o
.PHONY : source/ray/interaction.o

# target to build an object file
source/ray/interaction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/ray/interaction.cpp.o
.PHONY : source/ray/interaction.cpp.o

source/ray/interaction.i: source/ray/interaction.cpp.i
.PHONY : source/ray/interaction.i

# target to preprocess a source file
source/ray/interaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/ray/interaction.cpp.i
.PHONY : source/ray/interaction.cpp.i

source/ray/interaction.s: source/ray/interaction.cpp.s
.PHONY : source/ray/interaction.s

# target to generate assembly for a file
source/ray/interaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/ray/interaction.cpp.s
.PHONY : source/ray/interaction.cpp.s

source/ray/ray.o: source/ray/ray.cpp.o
.PHONY : source/ray/ray.o

# target to build an object file
source/ray/ray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/ray/ray.cpp.o
.PHONY : source/ray/ray.cpp.o

source/ray/ray.i: source/ray/ray.cpp.i
.PHONY : source/ray/ray.i

# target to preprocess a source file
source/ray/ray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/ray/ray.cpp.i
.PHONY : source/ray/ray.cpp.i

source/ray/ray.s: source/ray/ray.cpp.s
.PHONY : source/ray/ray.s

# target to generate assembly for a file
source/ray/ray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/ray/ray.cpp.s
.PHONY : source/ray/ray.cpp.s

source/scene/scene.o: source/scene/scene.cpp.o
.PHONY : source/scene/scene.o

# target to build an object file
source/scene/scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/scene/scene.cpp.o
.PHONY : source/scene/scene.cpp.o

source/scene/scene.i: source/scene/scene.cpp.i
.PHONY : source/scene/scene.i

# target to preprocess a source file
source/scene/scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/scene/scene.cpp.i
.PHONY : source/scene/scene.cpp.i

source/scene/scene.s: source/scene/scene.cpp.s
.PHONY : source/scene/scene.s

# target to generate assembly for a file
source/scene/scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/scene/scene.cpp.s
.PHONY : source/scene/scene.cpp.s

source/surface/quadric.o: source/surface/quadric.cpp.o
.PHONY : source/surface/quadric.o

# target to build an object file
source/surface/quadric.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/surface/quadric.cpp.o
.PHONY : source/surface/quadric.cpp.o

source/surface/quadric.i: source/surface/quadric.cpp.i
.PHONY : source/surface/quadric.i

# target to preprocess a source file
source/surface/quadric.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/surface/quadric.cpp.i
.PHONY : source/surface/quadric.cpp.i

source/surface/quadric.s: source/surface/quadric.cpp.s
.PHONY : source/surface/quadric.s

# target to generate assembly for a file
source/surface/quadric.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/surface/quadric.cpp.s
.PHONY : source/surface/quadric.cpp.s

source/surface/sphere.o: source/surface/sphere.cpp.o
.PHONY : source/surface/sphere.o

# target to build an object file
source/surface/sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/surface/sphere.cpp.o
.PHONY : source/surface/sphere.cpp.o

source/surface/sphere.i: source/surface/sphere.cpp.i
.PHONY : source/surface/sphere.i

# target to preprocess a source file
source/surface/sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/surface/sphere.cpp.i
.PHONY : source/surface/sphere.cpp.i

source/surface/sphere.s: source/surface/sphere.cpp.s
.PHONY : source/surface/sphere.s

# target to generate assembly for a file
source/surface/sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/surface/sphere.cpp.s
.PHONY : source/surface/sphere.cpp.s

source/surface/triangle.o: source/surface/triangle.cpp.o
.PHONY : source/surface/triangle.o

# target to build an object file
source/surface/triangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/surface/triangle.cpp.o
.PHONY : source/surface/triangle.cpp.o

source/surface/triangle.i: source/surface/triangle.cpp.i
.PHONY : source/surface/triangle.i

# target to preprocess a source file
source/surface/triangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/surface/triangle.cpp.i
.PHONY : source/surface/triangle.cpp.i

source/surface/triangle.s: source/surface/triangle.cpp.s
.PHONY : source/surface/triangle.s

# target to generate assembly for a file
source/surface/triangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte-carlo-ray-tracer.dir/build.make CMakeFiles/monte-carlo-ray-tracer.dir/source/surface/triangle.cpp.s
.PHONY : source/surface/triangle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... monte-carlo-ray-tracer"
	@echo "... source/bvh/bvh.o"
	@echo "... source/bvh/bvh.i"
	@echo "... source/bvh/bvh.s"
	@echo "... source/camera/camera.o"
	@echo "... source/camera/camera.i"
	@echo "... source/camera/camera.s"
	@echo "... source/camera/image.o"
	@echo "... source/camera/image.i"
	@echo "... source/camera/image.s"
	@echo "... source/camera/pixel-operators.o"
	@echo "... source/camera/pixel-operators.i"
	@echo "... source/camera/pixel-operators.s"
	@echo "... source/common/bounding-box.o"
	@echo "... source/common/bounding-box.i"
	@echo "... source/common/bounding-box.s"
	@echo "... source/common/coordinate-system.o"
	@echo "... source/common/coordinate-system.i"
	@echo "... source/common/coordinate-system.s"
	@echo "... source/common/format.o"
	@echo "... source/common/format.i"
	@echo "... source/common/format.s"
	@echo "... source/common/histogram.o"
	@echo "... source/common/histogram.i"
	@echo "... source/common/histogram.s"
	@echo "... source/common/option.o"
	@echo "... source/common/option.i"
	@echo "... source/common/option.s"
	@echo "... source/common/util.o"
	@echo "... source/common/util.i"
	@echo "... source/common/util.s"
	@echo "... source/integrator/integrator.o"
	@echo "... source/integrator/integrator.i"
	@echo "... source/integrator/integrator.s"
	@echo "... source/integrator/path-tracer/path-tracer.o"
	@echo "... source/integrator/path-tracer/path-tracer.i"
	@echo "... source/integrator/path-tracer/path-tracer.s"
	@echo "... source/integrator/photon-mapper/photon-mapper.o"
	@echo "... source/integrator/photon-mapper/photon-mapper.i"
	@echo "... source/integrator/photon-mapper/photon-mapper.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/material/fresnel.o"
	@echo "... source/material/fresnel.i"
	@echo "... source/material/fresnel.s"
	@echo "... source/material/ggx.o"
	@echo "... source/material/ggx.i"
	@echo "... source/material/ggx.s"
	@echo "... source/material/material.o"
	@echo "... source/material/material.i"
	@echo "... source/material/material.s"
	@echo "... source/octree/linear-octree.o"
	@echo "... source/octree/linear-octree.i"
	@echo "... source/octree/linear-octree.s"
	@echo "... source/octree/octree.o"
	@echo "... source/octree/octree.i"
	@echo "... source/octree/octree.s"
	@echo "... source/ray/interaction.o"
	@echo "... source/ray/interaction.i"
	@echo "... source/ray/interaction.s"
	@echo "... source/ray/ray.o"
	@echo "... source/ray/ray.i"
	@echo "... source/ray/ray.s"
	@echo "... source/scene/scene.o"
	@echo "... source/scene/scene.i"
	@echo "... source/scene/scene.s"
	@echo "... source/surface/quadric.o"
	@echo "... source/surface/quadric.i"
	@echo "... source/surface/quadric.s"
	@echo "... source/surface/sphere.o"
	@echo "... source/surface/sphere.i"
	@echo "... source/surface/sphere.s"
	@echo "... source/surface/triangle.o"
	@echo "... source/surface/triangle.i"
	@echo "... source/surface/triangle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

